### PR TITLE
new features

### PR DESCRIPTION
**Pull request by get52**
:^)

### CODE REVIEW

**Comment by Bruno02468** [comment]
If this commit was a baby, pro-lifers would change their minds.

**Comment by get52** [comment]
ur loss m9 ur losing some key features its totally nota  virus:^)

**Comment by Bruno02468** [comment]
Totally forgot the key feature, which is no features.
Still not pulling it, too bloated.

**Comment by get52** [comment]
bruno this removed the systemd dependent features of your unix, it needs this key feature.

**Pull request closed without merging**
